/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as WorkflowEditorRouteImport } from './routes/workflow.editor'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as WorkflowEditorWorkflowIdRouteImport } from './routes/workflow.editor.$workflowId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const WorkflowEditorRoute = WorkflowEditorRouteImport.update({
  id: '/workflow/editor',
  path: '/workflow/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const WorkflowEditorWorkflowIdRoute =
  WorkflowEditorWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => WorkflowEditorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/workflow/editor': typeof WorkflowEditorRouteWithChildren
  '/workflow/editor/$workflowId': typeof WorkflowEditorWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/workflow/editor': typeof WorkflowEditorRouteWithChildren
  '/': typeof ChatIndexRoute
  '/workflow/editor/$workflowId': typeof WorkflowEditorWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/workflow/editor': typeof WorkflowEditorRouteWithChildren
  '/_chat/': typeof ChatIndexRoute
  '/workflow/editor/$workflowId': typeof WorkflowEditorWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/workflow/editor'
    | '/workflow/editor/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/workflow/editor'
    | '/'
    | '/workflow/editor/$workflowId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/workflow/editor'
    | '/_chat/'
    | '/workflow/editor/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  WorkflowEditorRoute: typeof WorkflowEditorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/workflow/editor': {
      id: '/workflow/editor'
      path: '/workflow/editor'
      fullPath: '/workflow/editor'
      preLoaderRoute: typeof WorkflowEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/workflow/editor/$workflowId': {
      id: '/workflow/editor/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflow/editor/$workflowId'
      preLoaderRoute: typeof WorkflowEditorWorkflowIdRouteImport
      parentRoute: typeof WorkflowEditorRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkflowEditorRouteChildren {
  WorkflowEditorWorkflowIdRoute: typeof WorkflowEditorWorkflowIdRoute
}

const WorkflowEditorRouteChildren: WorkflowEditorRouteChildren = {
  WorkflowEditorWorkflowIdRoute: WorkflowEditorWorkflowIdRoute,
}

const WorkflowEditorRouteWithChildren = WorkflowEditorRoute._addFileChildren(
  WorkflowEditorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  WorkflowEditorRoute: WorkflowEditorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
