/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentModesRouteImport } from './routes/agent-modes'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as AgentModesWorkflowsRouteImport } from './routes/agent-modes.workflows'
import { Route as AgentModesDiscussionsRouteImport } from './routes/agent-modes.discussions'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as AgentModesWorkflowsIndexRouteImport } from './routes/agent-modes.workflows.index'
import { Route as AgentModesDiscussionsIndexRouteImport } from './routes/agent-modes.discussions.index'
import { Route as AgentModesWorkflowsWorkflowIdRouteImport } from './routes/agent-modes.workflows.$workflowId'
import { Route as AgentModesDiscussionsGlobalDiscussionNameRouteImport } from './routes/agent-modes.discussions.global.$discussionName'
import { Route as AgentModesDiscussionsProjectProjectIdDiscussionNameRouteImport } from './routes/agent-modes.discussions.project.$projectId.$discussionName'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentModesRoute = AgentModesRouteImport.update({
  id: '/agent-modes',
  path: '/agent-modes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const AgentModesWorkflowsRoute = AgentModesWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AgentModesRoute,
} as any)
const AgentModesDiscussionsRoute = AgentModesDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AgentModesRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const AgentModesWorkflowsIndexRoute =
  AgentModesWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AgentModesWorkflowsRoute,
  } as any)
const AgentModesDiscussionsIndexRoute =
  AgentModesDiscussionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AgentModesDiscussionsRoute,
  } as any)
const AgentModesWorkflowsWorkflowIdRoute =
  AgentModesWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => AgentModesWorkflowsRoute,
  } as any)
const AgentModesDiscussionsGlobalDiscussionNameRoute =
  AgentModesDiscussionsGlobalDiscussionNameRouteImport.update({
    id: '/global/$discussionName',
    path: '/global/$discussionName',
    getParentRoute: () => AgentModesDiscussionsRoute,
  } as any)
const AgentModesDiscussionsProjectProjectIdDiscussionNameRoute =
  AgentModesDiscussionsProjectProjectIdDiscussionNameRouteImport.update({
    id: '/project/$projectId/$discussionName',
    path: '/project/$projectId/$discussionName',
    getParentRoute: () => AgentModesDiscussionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/agent-modes': typeof AgentModesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/agent-modes/discussions': typeof AgentModesDiscussionsRouteWithChildren
  '/agent-modes/workflows': typeof AgentModesWorkflowsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/agent-modes/workflows/$workflowId': typeof AgentModesWorkflowsWorkflowIdRoute
  '/agent-modes/discussions/': typeof AgentModesDiscussionsIndexRoute
  '/agent-modes/workflows/': typeof AgentModesWorkflowsIndexRoute
  '/agent-modes/discussions/global/$discussionName': typeof AgentModesDiscussionsGlobalDiscussionNameRoute
  '/agent-modes/discussions/project/$projectId/$discussionName': typeof AgentModesDiscussionsProjectProjectIdDiscussionNameRoute
}
export interface FileRoutesByTo {
  '/agent-modes': typeof AgentModesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/agent-modes/workflows/$workflowId': typeof AgentModesWorkflowsWorkflowIdRoute
  '/agent-modes/discussions': typeof AgentModesDiscussionsIndexRoute
  '/agent-modes/workflows': typeof AgentModesWorkflowsIndexRoute
  '/agent-modes/discussions/global/$discussionName': typeof AgentModesDiscussionsGlobalDiscussionNameRoute
  '/agent-modes/discussions/project/$projectId/$discussionName': typeof AgentModesDiscussionsProjectProjectIdDiscussionNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/agent-modes': typeof AgentModesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/agent-modes/discussions': typeof AgentModesDiscussionsRouteWithChildren
  '/agent-modes/workflows': typeof AgentModesWorkflowsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/agent-modes/workflows/$workflowId': typeof AgentModesWorkflowsWorkflowIdRoute
  '/agent-modes/discussions/': typeof AgentModesDiscussionsIndexRoute
  '/agent-modes/workflows/': typeof AgentModesWorkflowsIndexRoute
  '/agent-modes/discussions/global/$discussionName': typeof AgentModesDiscussionsGlobalDiscussionNameRoute
  '/agent-modes/discussions/project/$projectId/$discussionName': typeof AgentModesDiscussionsProjectProjectIdDiscussionNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-modes'
    | '/settings'
    | '/$threadId'
    | '/agent-modes/discussions'
    | '/agent-modes/workflows'
    | '/settings/archived'
    | '/settings/general'
    | '/agent-modes/workflows/$workflowId'
    | '/agent-modes/discussions/'
    | '/agent-modes/workflows/'
    | '/agent-modes/discussions/global/$discussionName'
    | '/agent-modes/discussions/project/$projectId/$discussionName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agent-modes'
    | '/settings'
    | '/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/'
    | '/agent-modes/workflows/$workflowId'
    | '/agent-modes/discussions'
    | '/agent-modes/workflows'
    | '/agent-modes/discussions/global/$discussionName'
    | '/agent-modes/discussions/project/$projectId/$discussionName'
  id:
    | '__root__'
    | '/_chat'
    | '/agent-modes'
    | '/settings'
    | '/_chat/$threadId'
    | '/agent-modes/discussions'
    | '/agent-modes/workflows'
    | '/settings/archived'
    | '/settings/general'
    | '/_chat/'
    | '/agent-modes/workflows/$workflowId'
    | '/agent-modes/discussions/'
    | '/agent-modes/workflows/'
    | '/agent-modes/discussions/global/$discussionName'
    | '/agent-modes/discussions/project/$projectId/$discussionName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  AgentModesRoute: typeof AgentModesRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-modes': {
      id: '/agent-modes'
      path: '/agent-modes'
      fullPath: '/agent-modes'
      preLoaderRoute: typeof AgentModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/agent-modes/workflows': {
      id: '/agent-modes/workflows'
      path: '/workflows'
      fullPath: '/agent-modes/workflows'
      preLoaderRoute: typeof AgentModesWorkflowsRouteImport
      parentRoute: typeof AgentModesRoute
    }
    '/agent-modes/discussions': {
      id: '/agent-modes/discussions'
      path: '/discussions'
      fullPath: '/agent-modes/discussions'
      preLoaderRoute: typeof AgentModesDiscussionsRouteImport
      parentRoute: typeof AgentModesRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/agent-modes/workflows/': {
      id: '/agent-modes/workflows/'
      path: '/'
      fullPath: '/agent-modes/workflows/'
      preLoaderRoute: typeof AgentModesWorkflowsIndexRouteImport
      parentRoute: typeof AgentModesWorkflowsRoute
    }
    '/agent-modes/discussions/': {
      id: '/agent-modes/discussions/'
      path: '/'
      fullPath: '/agent-modes/discussions/'
      preLoaderRoute: typeof AgentModesDiscussionsIndexRouteImport
      parentRoute: typeof AgentModesDiscussionsRoute
    }
    '/agent-modes/workflows/$workflowId': {
      id: '/agent-modes/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/agent-modes/workflows/$workflowId'
      preLoaderRoute: typeof AgentModesWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AgentModesWorkflowsRoute
    }
    '/agent-modes/discussions/global/$discussionName': {
      id: '/agent-modes/discussions/global/$discussionName'
      path: '/global/$discussionName'
      fullPath: '/agent-modes/discussions/global/$discussionName'
      preLoaderRoute: typeof AgentModesDiscussionsGlobalDiscussionNameRouteImport
      parentRoute: typeof AgentModesDiscussionsRoute
    }
    '/agent-modes/discussions/project/$projectId/$discussionName': {
      id: '/agent-modes/discussions/project/$projectId/$discussionName'
      path: '/project/$projectId/$discussionName'
      fullPath: '/agent-modes/discussions/project/$projectId/$discussionName'
      preLoaderRoute: typeof AgentModesDiscussionsProjectProjectIdDiscussionNameRouteImport
      parentRoute: typeof AgentModesDiscussionsRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface AgentModesDiscussionsRouteChildren {
  AgentModesDiscussionsIndexRoute: typeof AgentModesDiscussionsIndexRoute
  AgentModesDiscussionsGlobalDiscussionNameRoute: typeof AgentModesDiscussionsGlobalDiscussionNameRoute
  AgentModesDiscussionsProjectProjectIdDiscussionNameRoute: typeof AgentModesDiscussionsProjectProjectIdDiscussionNameRoute
}

const AgentModesDiscussionsRouteChildren: AgentModesDiscussionsRouteChildren = {
  AgentModesDiscussionsIndexRoute: AgentModesDiscussionsIndexRoute,
  AgentModesDiscussionsGlobalDiscussionNameRoute:
    AgentModesDiscussionsGlobalDiscussionNameRoute,
  AgentModesDiscussionsProjectProjectIdDiscussionNameRoute:
    AgentModesDiscussionsProjectProjectIdDiscussionNameRoute,
}

const AgentModesDiscussionsRouteWithChildren =
  AgentModesDiscussionsRoute._addFileChildren(
    AgentModesDiscussionsRouteChildren,
  )

interface AgentModesWorkflowsRouteChildren {
  AgentModesWorkflowsWorkflowIdRoute: typeof AgentModesWorkflowsWorkflowIdRoute
  AgentModesWorkflowsIndexRoute: typeof AgentModesWorkflowsIndexRoute
}

const AgentModesWorkflowsRouteChildren: AgentModesWorkflowsRouteChildren = {
  AgentModesWorkflowsWorkflowIdRoute: AgentModesWorkflowsWorkflowIdRoute,
  AgentModesWorkflowsIndexRoute: AgentModesWorkflowsIndexRoute,
}

const AgentModesWorkflowsRouteWithChildren =
  AgentModesWorkflowsRoute._addFileChildren(AgentModesWorkflowsRouteChildren)

interface AgentModesRouteChildren {
  AgentModesDiscussionsRoute: typeof AgentModesDiscussionsRouteWithChildren
  AgentModesWorkflowsRoute: typeof AgentModesWorkflowsRouteWithChildren
}

const AgentModesRouteChildren: AgentModesRouteChildren = {
  AgentModesDiscussionsRoute: AgentModesDiscussionsRouteWithChildren,
  AgentModesWorkflowsRoute: AgentModesWorkflowsRouteWithChildren,
}

const AgentModesRouteWithChildren = AgentModesRoute._addFileChildren(
  AgentModesRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  AgentModesRoute: AgentModesRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
