import {
  ThreadPhaseStartedPayload as ContractsThreadPhaseStartedPayloadSchema,
  ThreadPhaseCompletedPayload as ContractsThreadPhaseCompletedPayloadSchema,
  ThreadPhaseFailedPayload as ContractsThreadPhaseFailedPayloadSchema,
  ThreadPhaseSkippedPayload as ContractsThreadPhaseSkippedPayloadSchema,
  ThreadPhaseOutputEditedPayload as ContractsThreadPhaseOutputEditedPayloadSchema,
  ThreadQualityCheckStartedPayload as ContractsThreadQualityCheckStartedPayloadSchema,
  ThreadQualityCheckCompletedPayload as ContractsThreadQualityCheckCompletedPayloadSchema,
  ThreadBootstrapQueuedPayload as ContractsThreadBootstrapQueuedPayloadSchema,
  ThreadBootstrapStartedPayload as ContractsThreadBootstrapStartedPayloadSchema,
  ThreadBootstrapCompletedPayload as ContractsThreadBootstrapCompletedPayloadSchema,
  ThreadBootstrapFailedPayload as ContractsThreadBootstrapFailedPayloadSchema,
  ThreadBootstrapSkippedPayload as ContractsThreadBootstrapSkippedPayloadSchema,
  ThreadCorrectionQueuedPayload as ContractsThreadCorrectionQueuedPayloadSchema,
  ThreadCorrectionDeliveredPayload as ContractsThreadCorrectionDeliveredPayloadSchema,
  ThreadLinkAddedPayload as ContractsThreadLinkAddedPayloadSchema,
  ThreadLinkRemovedPayload as ContractsThreadLinkRemovedPayloadSchema,
  ThreadPromotedPayload as ContractsThreadPromotedPayloadSchema,
  ThreadDependencyAddedPayload as ContractsThreadDependencyAddedPayloadSchema,
  ThreadDependencyRemovedPayload as ContractsThreadDependencyRemovedPayloadSchema,
  ThreadDependenciesSatisfiedPayload as ContractsThreadDependenciesSatisfiedPayloadSchema,
  ThreadSynthesisCompletedPayload as ContractsThreadSynthesisCompletedPayloadSchema,
  ChannelCreatedPayload as ContractsChannelCreatedPayloadSchema,
  ChannelMessagePostedPayload as ContractsChannelMessagePostedPayloadSchema,
  ChannelMessagesReadPayload as ContractsChannelMessagesReadPayloadSchema,
  ChannelConclusionProposedPayload as ContractsChannelConclusionProposedPayloadSchema,
  ChannelConcludedPayload as ContractsChannelConcludedPayloadSchema,
  ChannelClosedPayload as ContractsChannelClosedPayloadSchema,
  InteractiveRequestOpenedPayload as ContractsInteractiveRequestOpenedPayloadSchema,
  InteractiveRequestResolvedPayload as ContractsInteractiveRequestResolvedPayloadSchema,
  InteractiveRequestStalePayload as ContractsInteractiveRequestStalePayloadSchema,
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;

export const ThreadPhaseStartedPayload = ContractsThreadPhaseStartedPayloadSchema;
export const ThreadPhaseCompletedPayload = ContractsThreadPhaseCompletedPayloadSchema;
export const ThreadPhaseFailedPayload = ContractsThreadPhaseFailedPayloadSchema;
export const ThreadPhaseSkippedPayload = ContractsThreadPhaseSkippedPayloadSchema;
export const ThreadPhaseOutputEditedPayload = ContractsThreadPhaseOutputEditedPayloadSchema;
export const ThreadQualityCheckStartedPayload = ContractsThreadQualityCheckStartedPayloadSchema;
export const ThreadQualityCheckCompletedPayload = ContractsThreadQualityCheckCompletedPayloadSchema;
export const ThreadBootstrapQueuedPayload = ContractsThreadBootstrapQueuedPayloadSchema;
export const ThreadBootstrapStartedPayload = ContractsThreadBootstrapStartedPayloadSchema;
export const ThreadBootstrapCompletedPayload = ContractsThreadBootstrapCompletedPayloadSchema;
export const ThreadBootstrapFailedPayload = ContractsThreadBootstrapFailedPayloadSchema;
export const ThreadBootstrapSkippedPayload = ContractsThreadBootstrapSkippedPayloadSchema;
export const ThreadCorrectionQueuedPayload = ContractsThreadCorrectionQueuedPayloadSchema;
export const ThreadCorrectionDeliveredPayload = ContractsThreadCorrectionDeliveredPayloadSchema;
export const ThreadLinkAddedPayload = ContractsThreadLinkAddedPayloadSchema;
export const ThreadLinkRemovedPayload = ContractsThreadLinkRemovedPayloadSchema;
export const ThreadPromotedPayload = ContractsThreadPromotedPayloadSchema;
export const ThreadDependencyAddedPayload = ContractsThreadDependencyAddedPayloadSchema;
export const ThreadDependencyRemovedPayload = ContractsThreadDependencyRemovedPayloadSchema;
export const ThreadDependenciesSatisfiedPayload = ContractsThreadDependenciesSatisfiedPayloadSchema;
export const ThreadSynthesisCompletedPayload = ContractsThreadSynthesisCompletedPayloadSchema;
export const ChannelCreatedPayload = ContractsChannelCreatedPayloadSchema;
export const ChannelMessagePostedPayload = ContractsChannelMessagePostedPayloadSchema;
export const ChannelMessagesReadPayload = ContractsChannelMessagesReadPayloadSchema;
export const ChannelConclusionProposedPayload = ContractsChannelConclusionProposedPayloadSchema;
export const ChannelConcludedPayload = ContractsChannelConcludedPayloadSchema;
export const ChannelClosedPayload = ContractsChannelClosedPayloadSchema;
export const InteractiveRequestOpenedPayload = ContractsInteractiveRequestOpenedPayloadSchema;
export const InteractiveRequestResolvedPayload = ContractsInteractiveRequestResolvedPayloadSchema;
export const InteractiveRequestStalePayload = ContractsInteractiveRequestStalePayloadSchema;
